version: '2'
services:
  db:
    image: postgres
#  web:
#    build: .
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/code
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db


  web:
    restart: always
    build: .
#    expose:
#      - "8000"
#    links:
#      - postgres:postgres
#      - redis:redis
#    volumes:
#      - /usr/src/app
#      - /usr/src/app/static
    depends_on:
      - db
#    env_file: .env
    command: /usr/local/bin/gunicorn soloha.wsgi:application -w 3 -b :8000

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web

#  postgres:
#    restart: always
#    image: postgres:latest
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data/

#  redis:
#    restart: always
#    image: redis:latest
#    ports:
#      - "6379:6379"
#    volumes:
#      - redisdata:/data
