// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(grunt) {
    grunt.initConfig({
      pkg: grunt.file.readJSON('package.json'),
      catalogue_coffee: {
        files: {
          src: ['apps/catalogue/**/*.coffee'],
          dest: 'static/build/js/catalogue/script.js'
        }
      },
      promotions_coffee: {
        files: {
          src: ['apps/promotions/**/*.coffee'],
          dest: 'static/build/js/promotions/script.js'
        }
      },
      common_coffee: {
        files: {
          src: ['soloha/**/*.coffee'],
          dest: 'static/build/js/common/script.js'
        }
      },
      less: {
        development: {
          options: {
            paths: ["assets/css"]
          },
          files: {
            "static/build/css/main.css": "static/src/less/main.less"
          }
        },
        production: {
          options: {
            paths: ["assets/css"],
            cleancss: true
          },
          files: {
            "path/to/result.css": "path/to/source.less"
          }
        }
      },
      min: {
        dist: {
          src: [],
          dest: ''
        }
      },
      cssmin: {
        dist: {
          src: [],
          dest: ''
        }
      }
    });
    grunt.loadNpmTasks('grunt-contrib-coffee');
    grunt.loadNpmTasks('grunt-contrib-less');
    return grunt.registerTask('default', ['common_coffee:files', 'promotions_coffee:files', 'catalogue_coffee:files', 'less']);
  };

}).call(this);
