// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(grunt) {
    grunt.initConfig({
      pkg: grunt.file.readJSON('package.json'),
      coffee: {
        files: {
          src: ['apps/**/*.coffee'],
          dest: 'static/build/js/script.js'
        }
      },
      common_coffee: {
        files: {
          src: ['soloha/**/*.coffee'],
          dest: 'static/build/js/common/script.js'
        }
      },
      less: {
        development: {
          options: {
            paths: ["assets/css"]
          },
          files: {
            "static/build/css/main.css": "static/src/less/main.less"
          }
        },
        production: {
          options: {
            paths: ["assets/css"],
            cleancss: true
          },
          files: {
            "path/to/result.css": "path/to/source.less"
          }
        }
      },
      min: {
        dist: {
          src: [],
          dest: ''
        }
      },
      cssmin: {
        dist: {
          src: [],
          dest: ''
        }
      }
    });
    grunt.loadNpmTasks('grunt-contrib-coffee');
    grunt.loadNpmTasks('grunt-contrib-less');
    grunt.registerTask('default', ['coffee:files', 'less']);
    return grunt.registerTask('compile', ['common_coffee']);
  };

}).call(this);
